//
//  Country.swift
//  Random
//
//  Created by シンジャスティン on 2026/02/05.
//

import Foundation

struct Country: Identifiable, Hashable {
    var id = UUID()
    var nameKey: String // Localization key
    var name: String {
        NSLocalizedString(nameKey, comment: "")
    }
    var isoCode: String
    var countryCode: String
    var timeZone: String

    static let allCountries: [Country] = [
        Country(nameKey: "Country.Afghanistan", isoCode: "AF", countryCode: "+93", timeZone: "GMT+4:30"),
        Country(nameKey: "Country.Albania", isoCode: "AL", countryCode: "+355", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Algeria", isoCode: "DZ", countryCode: "+213", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Andorra", isoCode: "AD", countryCode: "+376", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Angola", isoCode: "AO", countryCode: "+244", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.AntiguaAndBarbuda", isoCode: "AG", countryCode: "+1-268", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Argentina", isoCode: "AR", countryCode: "+54", timeZone: "GMT-3:00"),
        Country(nameKey: "Country.Armenia", isoCode: "AM", countryCode: "+374", timeZone: "GMT+4:00"),
        Country(nameKey: "Country.Australia", isoCode: "AU", countryCode: "+61", timeZone: "GMT+10:00"),
        Country(nameKey: "Country.Austria", isoCode: "AT", countryCode: "+43", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Azerbaijan", isoCode: "AZ", countryCode: "+994", timeZone: "GMT+4:00"),
        Country(nameKey: "Country.Bahamas", isoCode: "BS", countryCode: "+1-242", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Bahrain", isoCode: "BH", countryCode: "+973", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Bangladesh", isoCode: "BD", countryCode: "+880", timeZone: "GMT+6:00"),
        Country(nameKey: "Country.Barbados", isoCode: "BB", countryCode: "+1-246", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Belarus", isoCode: "BY", countryCode: "+375", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Belgium", isoCode: "BE", countryCode: "+32", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Belize", isoCode: "BZ", countryCode: "+501", timeZone: "GMT-6:00"),
        Country(nameKey: "Country.Benin", isoCode: "BJ", countryCode: "+229", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Bhutan", isoCode: "BT", countryCode: "+975", timeZone: "GMT+6:00"),
        Country(nameKey: "Country.Bolivia", isoCode: "BO", countryCode: "+591", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.BosniaAndHerzegovina", isoCode: "BA", countryCode: "+387", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Botswana", isoCode: "BW", countryCode: "+267", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Brazil", isoCode: "BR", countryCode: "+55", timeZone: "GMT-3:00"),
        Country(nameKey: "Country.Brunei", isoCode: "BN", countryCode: "+673", timeZone: "GMT+8:00"),
        Country(nameKey: "Country.Bulgaria", isoCode: "BG", countryCode: "+359", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.BurkinaFaso", isoCode: "BF", countryCode: "+226", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Burundi", isoCode: "BI", countryCode: "+257", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.CaboVerde", isoCode: "CV", countryCode: "+238", timeZone: "GMT-1:00"),
        Country(nameKey: "Country.Cambodia", isoCode: "KH", countryCode: "+855", timeZone: "GMT+7:00"),
        Country(nameKey: "Country.Cameroon", isoCode: "CM", countryCode: "+237", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Canada", isoCode: "CA", countryCode: "+1", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.CentralAfricanRepublic", isoCode: "CF", countryCode: "+236", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Chad", isoCode: "TD", countryCode: "+235", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Chile", isoCode: "CL", countryCode: "+56", timeZone: "GMT-3:00"),
        Country(nameKey: "Country.China", isoCode: "CN", countryCode: "+86", timeZone: "GMT+8:00"),
        Country(nameKey: "Country.Colombia", isoCode: "CO", countryCode: "+57", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Comoros", isoCode: "KM", countryCode: "+269", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.CongoBrazzaville", isoCode: "CG", countryCode: "+242", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.CongoKinshasa", isoCode: "CD", countryCode: "+243", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.CostaRica", isoCode: "CR", countryCode: "+506", timeZone: "GMT-6:00"),
        Country(nameKey: "Country.Croatia", isoCode: "HR", countryCode: "+385", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Cuba", isoCode: "CU", countryCode: "+53", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Cyprus", isoCode: "CY", countryCode: "+357", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.CzechRepublic", isoCode: "CZ", countryCode: "+420", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Denmark", isoCode: "DK", countryCode: "+45", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Djibouti", isoCode: "DJ", countryCode: "+253", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Dominica", isoCode: "DM", countryCode: "+1-767", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.DominicanRepublic", isoCode: "DO", countryCode: "+1-809", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.DPRKorea", isoCode: "KP", countryCode: "+850", timeZone: "GMT+9:00"),
        Country(nameKey: "Country.Ecuador", isoCode: "EC", countryCode: "+593", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Egypt", isoCode: "EG", countryCode: "+20", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.ElSalvador", isoCode: "SV", countryCode: "+503", timeZone: "GMT-6:00"),
        Country(nameKey: "Country.EquatorialGuinea", isoCode: "GQ", countryCode: "+240", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Eritrea", isoCode: "ER", countryCode: "+291", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Estonia", isoCode: "EE", countryCode: "+372", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Eswatini", isoCode: "SZ", countryCode: "+268", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Ethiopia", isoCode: "ET", countryCode: "+251", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Fiji", isoCode: "FJ", countryCode: "+679", timeZone: "GMT+12:00"),
        Country(nameKey: "Country.Finland", isoCode: "FI", countryCode: "+358", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.France", isoCode: "FR", countryCode: "+33", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Gabon", isoCode: "GA", countryCode: "+241", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Gambia", isoCode: "GM", countryCode: "+220", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Georgia", isoCode: "GE", countryCode: "+995", timeZone: "GMT+4:00"),
        Country(nameKey: "Country.Germany", isoCode: "DE", countryCode: "+49", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Ghana", isoCode: "GH", countryCode: "+233", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Greece", isoCode: "GR", countryCode: "+30", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Grenada", isoCode: "GD", countryCode: "+1-473", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Guatemala", isoCode: "GT", countryCode: "+502", timeZone: "GMT-6:00"),
        Country(nameKey: "Country.Guinea", isoCode: "GN", countryCode: "+224", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.GuineaBissau", isoCode: "GW", countryCode: "+245", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Guyana", isoCode: "GY", countryCode: "+592", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Haiti", isoCode: "HT", countryCode: "+509", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Honduras", isoCode: "HN", countryCode: "+504", timeZone: "GMT-6:00"),
        Country(nameKey: "Country.Hungary", isoCode: "HU", countryCode: "+36", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Iceland", isoCode: "IS", countryCode: "+354", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.India", isoCode: "IN", countryCode: "+91", timeZone: "GMT+5:30"),
        Country(nameKey: "Country.Indonesia", isoCode: "ID", countryCode: "+62", timeZone: "GMT+7:00"),
        Country(nameKey: "Country.Iran", isoCode: "IR", countryCode: "+98", timeZone: "GMT+3:30"),
        Country(nameKey: "Country.Iraq", isoCode: "IQ", countryCode: "+964", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Ireland", isoCode: "IE", countryCode: "+353", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Israel", isoCode: "IL", countryCode: "+972", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Italy", isoCode: "IT", countryCode: "+39", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.IvoryCoast", isoCode: "CI", countryCode: "+225", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Jamaica", isoCode: "JM", countryCode: "+1-876", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Japan", isoCode: "JP", countryCode: "+81", timeZone: "GMT+9:00"),
        Country(nameKey: "Country.Jordan", isoCode: "JO", countryCode: "+962", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Kazakhstan", isoCode: "KZ", countryCode: "+7", timeZone: "GMT+6:00"),
        Country(nameKey: "Country.Kenya", isoCode: "KE", countryCode: "+254", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Kiribati", isoCode: "KI", countryCode: "+686", timeZone: "GMT+12:00"),
        Country(nameKey: "Country.Kosovo", isoCode: "XK", countryCode: "+383", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Kuwait", isoCode: "KW", countryCode: "+965", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Kyrgyzstan", isoCode: "KG", countryCode: "+996", timeZone: "GMT+6:00"),
        Country(nameKey: "Country.Laos", isoCode: "LA", countryCode: "+856", timeZone: "GMT+7:00"),
        Country(nameKey: "Country.Latvia", isoCode: "LV", countryCode: "+371", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Lebanon", isoCode: "LB", countryCode: "+961", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Lesotho", isoCode: "LS", countryCode: "+266", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Liberia", isoCode: "LR", countryCode: "+231", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Libya", isoCode: "LY", countryCode: "+218", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Liechtenstein", isoCode: "LI", countryCode: "+423", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Lithuania", isoCode: "LT", countryCode: "+370", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Luxembourg", isoCode: "LU", countryCode: "+352", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Madagascar", isoCode: "MG", countryCode: "+261", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Malawi", isoCode: "MW", countryCode: "+265", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Malaysia", isoCode: "MY", countryCode: "+60", timeZone: "GMT+8:00"),
        Country(nameKey: "Country.Maldives", isoCode: "MV", countryCode: "+960", timeZone: "GMT+5:00"),
        Country(nameKey: "Country.Mali", isoCode: "ML", countryCode: "+223", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Malta", isoCode: "MT", countryCode: "+356", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.MarshallIslands", isoCode: "MH", countryCode: "+692", timeZone: "GMT+12:00"),
        Country(nameKey: "Country.Mauritania", isoCode: "MR", countryCode: "+222", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Mauritius", isoCode: "MU", countryCode: "+230", timeZone: "GMT+4:00"),
        Country(nameKey: "Country.Mexico", isoCode: "MX", countryCode: "+52", timeZone: "GMT-6:00"),
        Country(nameKey: "Country.Micronesia", isoCode: "FM", countryCode: "+691", timeZone: "GMT+11:00"),
        Country(nameKey: "Country.Moldova", isoCode: "MD", countryCode: "+373", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Monaco", isoCode: "MC", countryCode: "+377", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Mongolia", isoCode: "MN", countryCode: "+976", timeZone: "GMT+8:00"),
        Country(nameKey: "Country.Montenegro", isoCode: "ME", countryCode: "+382", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Morocco", isoCode: "MA", countryCode: "+212", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Mozambique", isoCode: "MZ", countryCode: "+258", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Myanmar", isoCode: "MM", countryCode: "+95", timeZone: "GMT+6:30"),
        Country(nameKey: "Country.Namibia", isoCode: "NA", countryCode: "+264", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Nauru", isoCode: "NR", countryCode: "+674", timeZone: "GMT+12:00"),
        Country(nameKey: "Country.Nepal", isoCode: "NP", countryCode: "+977", timeZone: "GMT+5:45"),
        Country(nameKey: "Country.Netherlands", isoCode: "NL", countryCode: "+31", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.NewZealand", isoCode: "NZ", countryCode: "+64", timeZone: "GMT+12:00"),
        Country(nameKey: "Country.Nicaragua", isoCode: "NI", countryCode: "+505", timeZone: "GMT-6:00"),
        Country(nameKey: "Country.Niger", isoCode: "NE", countryCode: "+227", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Nigeria", isoCode: "NG", countryCode: "+234", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.NorthMacedonia", isoCode: "MK", countryCode: "+389", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Norway", isoCode: "NO", countryCode: "+47", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Oman", isoCode: "OM", countryCode: "+968", timeZone: "GMT+4:00"),
        Country(nameKey: "Country.Pakistan", isoCode: "PK", countryCode: "+92", timeZone: "GMT+5:00"),
        Country(nameKey: "Country.Palau", isoCode: "PW", countryCode: "+680", timeZone: "GMT+9:00"),
        Country(nameKey: "Country.Palestine", isoCode: "PS", countryCode: "+970", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Panama", isoCode: "PA", countryCode: "+507", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.PapuaNewGuinea", isoCode: "PG", countryCode: "+675", timeZone: "GMT+10:00"),
        Country(nameKey: "Country.Paraguay", isoCode: "PY", countryCode: "+595", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Peru", isoCode: "PE", countryCode: "+51", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Philippines", isoCode: "PH", countryCode: "+63", timeZone: "GMT+8:00"),
        Country(nameKey: "Country.Poland", isoCode: "PL", countryCode: "+48", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Portugal", isoCode: "PT", countryCode: "+351", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Qatar", isoCode: "QA", countryCode: "+974", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Romania", isoCode: "RO", countryCode: "+40", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Russia", isoCode: "RU", countryCode: "+7", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Rwanda", isoCode: "RW", countryCode: "+250", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.SaintKittsAndNevis", isoCode: "KN", countryCode: "+1-869", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.SaintLucia", isoCode: "LC", countryCode: "+1-758", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.SaintVincentAndTheGrenadines", isoCode: "VC", countryCode: "+1-784", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Samoa", isoCode: "WS", countryCode: "+685", timeZone: "GMT+13:00"),
        Country(nameKey: "Country.SanMarino", isoCode: "SM", countryCode: "+378", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.SaoTomeAndPrincipe", isoCode: "ST", countryCode: "+239", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.SaudiArabia", isoCode: "SA", countryCode: "+966", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Senegal", isoCode: "SN", countryCode: "+221", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Serbia", isoCode: "RS", countryCode: "+381", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Seychelles", isoCode: "SC", countryCode: "+248", timeZone: "GMT+4:00"),
        Country(nameKey: "Country.SierraLeone", isoCode: "SL", countryCode: "+232", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Singapore", isoCode: "SG", countryCode: "+65", timeZone: "GMT+8:00"),
        Country(nameKey: "Country.Slovakia", isoCode: "SK", countryCode: "+421", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Slovenia", isoCode: "SI", countryCode: "+386", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.SolomonIslands", isoCode: "SB", countryCode: "+677", timeZone: "GMT+11:00"),
        Country(nameKey: "Country.Somalia", isoCode: "SO", countryCode: "+252", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.SouthAfrica", isoCode: "ZA", countryCode: "+27", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.SouthKorea", isoCode: "KR", countryCode: "+82", timeZone: "GMT+9:00"),
        Country(nameKey: "Country.SouthSudan", isoCode: "SS", countryCode: "+211", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Spain", isoCode: "ES", countryCode: "+34", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.SriLanka", isoCode: "LK", countryCode: "+94", timeZone: "GMT+5:30"),
        Country(nameKey: "Country.Sudan", isoCode: "SD", countryCode: "+249", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Suriname", isoCode: "SR", countryCode: "+597", timeZone: "GMT-3:00"),
        Country(nameKey: "Country.Sweden", isoCode: "SE", countryCode: "+46", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Switzerland", isoCode: "CH", countryCode: "+41", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Syria", isoCode: "SY", countryCode: "+963", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Taiwan", isoCode: "TW", countryCode: "+886", timeZone: "GMT+8:00"),
        Country(nameKey: "Country.Tajikistan", isoCode: "TJ", countryCode: "+992", timeZone: "GMT+5:00"),
        Country(nameKey: "Country.Tanzania", isoCode: "TZ", countryCode: "+255", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Thailand", isoCode: "TH", countryCode: "+66", timeZone: "GMT+7:00"),
        Country(nameKey: "Country.TimorLeste", isoCode: "TL", countryCode: "+670", timeZone: "GMT+9:00"),
        Country(nameKey: "Country.Togo", isoCode: "TG", countryCode: "+228", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.Tonga", isoCode: "TO", countryCode: "+676", timeZone: "GMT+13:00"),
        Country(nameKey: "Country.TrinidadAndTobago", isoCode: "TT", countryCode: "+1-868", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Tunisia", isoCode: "TN", countryCode: "+216", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Turkey", isoCode: "TR", countryCode: "+90", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Turkmenistan", isoCode: "TM", countryCode: "+993", timeZone: "GMT+5:00"),
        Country(nameKey: "Country.Tuvalu", isoCode: "TV", countryCode: "+688", timeZone: "GMT+12:00"),
        Country(nameKey: "Country.Uganda", isoCode: "UG", countryCode: "+256", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Ukraine", isoCode: "UA", countryCode: "+380", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.UnitedArabEmirates", isoCode: "AE", countryCode: "+971", timeZone: "GMT+4:00"),
        Country(nameKey: "Country.UnitedKingdom", isoCode: "GB", countryCode: "+44", timeZone: "GMT+0:00"),
        Country(nameKey: "Country.UnitedStates", isoCode: "US", countryCode: "+1", timeZone: "GMT-5:00"),
        Country(nameKey: "Country.Uruguay", isoCode: "UY", countryCode: "+598", timeZone: "GMT-3:00"),
        Country(nameKey: "Country.Uzbekistan", isoCode: "UZ", countryCode: "+998", timeZone: "GMT+5:00"),
        Country(nameKey: "Country.Vanuatu", isoCode: "VU", countryCode: "+678", timeZone: "GMT+11:00"),
        Country(nameKey: "Country.VaticanCity", isoCode: "VA", countryCode: "+379", timeZone: "GMT+1:00"),
        Country(nameKey: "Country.Venezuela", isoCode: "VE", countryCode: "+58", timeZone: "GMT-4:00"),
        Country(nameKey: "Country.Vietnam", isoCode: "VN", countryCode: "+84", timeZone: "GMT+7:00"),
        Country(nameKey: "Country.Yemen", isoCode: "YE", countryCode: "+967", timeZone: "GMT+3:00"),
        Country(nameKey: "Country.Zambia", isoCode: "ZM", countryCode: "+260", timeZone: "GMT+2:00"),
        Country(nameKey: "Country.Zimbabwe", isoCode: "ZW", countryCode: "+263", timeZone: "GMT+2:00")
    ]
}
